#!/usr/bin/env bash
# ============================================================
# ZTeasy — generate the local development secrets (ADR-037)
# ============================================================
# The repository carries no secret values, not even "obviously local" ones:
# a default committed to a public repo is a published credential, and this
# project shipped one to a live deployment before anyone noticed (ADR-037).
#
# This writes a gitignored `.env` in the repo root with fresh random values.
# Both Spring (via spring-dotenv) and `docker compose` read that same file, so
# one command makes a fresh clone runnable.
#
# Idempotent: an existing key is never overwritten, so re-running after adding
# a new variable tops up the file instead of invalidating everything already
# issued (certificates and an imported Keycloak realm both depend on these
# values matching what is already on disk).
#
# Usage: ./scripts/generate-dev-secrets.sh [--force]
#        --force   replace every value, even ones already present
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

ENV_FILE=".env"
FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

# name -> generator. Passwords for the demo humans are readable-ish on purpose:
# they get typed into a login form during a demo, not pasted.
random_secret() { python3 -c 'import secrets; print(secrets.token_urlsafe(32))'; }
random_password() { python3 -c 'import secrets; print(secrets.token_urlsafe(12))'; }

KEYS_SECRET=(
  ZTE_OBO_SECRET                          # HMAC key for X-ZTE-User-Context (ADR-004)
  ZTE_INTERNAL_API_KEY                    # /api/v1/internal/** shared secret (ADR-027)
  ZTE_SECRET_ZTE_GATEWAY                  # OIDC client secrets — must match the realm
  ZTE_SECRET_AGENT_A
  ZTE_SECRET_AGENT_B
  ZTE_SECRET_SERVICE_A
  ZTE_SECRET_CRM_ACCOUNT_HEALTH_EMEA_01
)
KEYS_PASSWORD=(
  DB_PASSWORD                             # Postgres role password
  ZTE_KEY_PASSWORD                        # PKCS12 keystore/truststore password
  KEYCLOAK_ADMIN_PASSWORD
  ZTE_PW_ZTE_ADMIN
  ZTE_PW_ZTE_TEST_USER
  ZTE_PW_ZTE_CEO
  ZTE_PW_ZTE_CFO
  ZTE_PW_ZTE_CTO
  ZTE_PW_ZTE_BOARD
  ZTE_PW_ZTE_DPO
)

touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

if ! grep -q '^# ZTeasy local development secrets' "$ENV_FILE" 2>/dev/null; then
  {
    printf '# ZTeasy local development secrets — generated by scripts/generate-dev-secrets.sh\n'
    printf '# Gitignored. Never commit, never paste into an issue. Regenerate freely on a\n'
    printf '# throwaway environment; on one you have already run, see the note in ADR-037\n'
    printf '# about certificates and the imported realm depending on these values.\n\n'
    cat "$ENV_FILE"
  } > "$ENV_FILE.tmp"
  mv "$ENV_FILE.tmp" "$ENV_FILE"
fi

# A file whose last line has no newline would swallow the first key appended to
# it — which is exactly what the first version of this script did to
# ANTHROPIC_API_KEY. Cheap to guarantee, expensive to debug.
[ -s "$ENV_FILE" ] && [ -n "$(tail -c 1 "$ENV_FILE")" ] && printf '\n' >> "$ENV_FILE"

added=0
put() {   # put <key> <value>
  local key=$1 value=$2
  if grep -qE "^${key}=" "$ENV_FILE"; then
    [ "$FORCE" -eq 0 ] && return 0
    grep -vE "^${key}=" "$ENV_FILE" > "$ENV_FILE.tmp" && mv "$ENV_FILE.tmp" "$ENV_FILE"
  fi
  printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  added=$((added + 1))
}

for key in "${KEYS_SECRET[@]}";   do put "$key" "$(random_secret)";   done
for key in "${KEYS_PASSWORD[@]}"; do put "$key" "$(random_password)"; done

# ANTHROPIC_API_KEY is a real external credential — nothing can generate it.
if ! grep -qE '^ANTHROPIC_API_KEY=' "$ENV_FILE"; then
  printf '\n# Your own Anthropic key — zt-agents will not start without it (ADR-008)\nANTHROPIC_API_KEY=\n' >> "$ENV_FILE"
fi

chmod 600 "$ENV_FILE"
echo "$ENV_FILE: ${added} value(s) written"
if [ "$added" -gt 0 ]; then
  cat <<'NEXT'

Next, because these values are baked into things that already exist:
  ./certs/generate-certs.sh                     # keystores use ZTE_KEY_PASSWORD
  python3 deploy/azure/make-cloud-realm.py --local   # realm carries the client secrets
  docker compose down -v && docker compose up -d     # Postgres keeps its old password otherwise
NEXT
fi
