#!/usr/bin/env bash
# ============================================================
# set-keycloak-password.sh
# Sets the initial password for zte-admin in zte-realm.
#
# Normally unnecessary since ADR-037: the realm generated by
# `make-cloud-realm.py --local` already carries every demo user's password from
# .env, and Keycloak imports it on first start. Use this to reset a password
# without re-importing the realm.
#
# Values come from .env (scripts/generate-dev-secrets.sh) — there are no
# defaults, because a default password in a public repository is a published
# password, which is how this project ended up with one guarding a live
# deployment (ADR-037).
#
# Usage: ./scripts/set-keycloak-password.sh
# ============================================================
set -euo pipefail

KEYCLOAK_URL="${KEYCLOAK_URL:-http://localhost:8180}"
# kcadm.sh runs via `docker exec`, i.e. *inside* the container's own network
# namespace — the host-side 8180 mapping doesn't exist there, only the
# container's actual listener (KC_HTTP_PORT, 8080).
KEYCLOAK_INTERNAL_URL="${KEYCLOAK_INTERNAL_URL:-http://localhost:8080}"
ADMIN_USER="${KEYCLOAK_ADMIN:-admin}"
ADMIN_PASS="${KEYCLOAK_ADMIN_PASSWORD:?set it in .env — run scripts/generate-dev-secrets.sh}"
REALM="zte-realm"

# username -> env var holding its password, the same mapping make-cloud-realm.py
# uses, so the two ways of setting a password cannot disagree.
declare -A USERS=(
  [zte-admin]=ZTE_PW_ZTE_ADMIN
  [zte-test-user]=ZTE_PW_ZTE_TEST_USER
  [zte-ceo]=ZTE_PW_ZTE_CEO
  [zte-cfo]=ZTE_PW_ZTE_CFO
  [zte-cto]=ZTE_PW_ZTE_CTO
  [zte-board]=ZTE_PW_ZTE_BOARD
  [zte-dpo]=ZTE_PW_ZTE_DPO
)

echo "[zte-init] Waiting for Keycloak at ${KEYCLOAK_URL} ..."
until curl -sf "${KEYCLOAK_URL}/health/ready" > /dev/null 2>&1; do
  sleep 2
done
echo "[zte-init] Keycloak is ready."

echo "[zte-init] Authenticating admin CLI ..."
docker exec zte-keycloak /opt/keycloak/bin/kcadm.sh config credentials \
  --server "${KEYCLOAK_INTERNAL_URL}" \
  --realm master \
  --user "${ADMIN_USER}" \
  --password "${ADMIN_PASS}"

for user in "${!USERS[@]}"; do
  var="${USERS[$user]}"
  pass="${!var:?}"
  echo "[zte-init] Setting password for '${user}' (from ${var}) ..."
  docker exec zte-keycloak /opt/keycloak/bin/kcadm.sh set-password \
    --target-realm "${REALM}" \
    --username "${user}" \
    --new-password "${pass}"
done

# Passwords are deliberately not echoed — they are in .env, which is where a
# person should read them from (ADR-037).
echo "[zte-init] Done for ${#USERS[@]} users. Passwords are in .env."
echo "[zte-init] Token endpoint: ${KEYCLOAK_URL}/realms/${REALM}/protocol/openid-connect/token"
